server:
  port: 8080

spring:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
  profiles:
    active: dev
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
    url: jdbc:mysql://localhost:3306/myproject #数据源地址  ?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root # 用户名
    password: 123456a? # 密码



my:
  servlet:
    multipart:
      max-file-size: 100MB



#    ds1: #数据源1
#      driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
#      url: jdbc:mysql://localhost:3306/world #数据源地址
#      username: root # 用户名
#      password: 123456a? # 密码
#    ds2: # 数据源2
#      driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
#      url: jdbc:sqlserver://localhost;DatabaseName=project;#数据源地址
#      username: sa # 用户名
#      password: 123456a? # 密码